name: Fetch latest translations

on:
  schedule:
    - cron: "10,40 * * * *"
      timezone: UTC

  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Upload translations source file
        uses: crowdin/github-action@v2
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          CROWDIN_BASE_PATH: ${{ github.workspace }}
        with:
          command: 'download'
          command_args: '--config dev/crowdin.yml --all'

      - name: Generate metadata
        run: |
          rm -f metadata.json
          bash ./dev/generate-metadata.sh

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: ${{ github.ref_name }}
          commit_message: 'chore: fetch localization files from Crowdin'
          file_pattern: '*.json'
